### ISSUE TITLE
little bug in Examples

### ISSUE THREAD

**Issue by LiaoXiaoQiang** [loadingvx/clib#12]
in log.usage.c
"int i = 0" should be declared outside for-loop.
Don't beat me if I am wrong...

**Comment by loadingvx** [comment]
try gcc --std=c99
Dont't let these things bother you. it will be a best practice always using g++.
However, sometimes earlier this had been fixed. 

Plz run this:

git remote add owner git@github.com:loadingvx/clib.git
git pull --rebase owner master
git push origin master
then refresh your github/clib repo page.

**Comment by loadingvx** [comment]
If you have any free time, change all these to c90. 
Most of these codes are only tested on my mac, so PR for bugs are welcomed.
